# Generated by Django 4.2.2 on 2025-04-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('doing', 'Doing'), ('done', 'Done'), ('pending', 'Pending')], default='pending', max_length=7),
        ),
    ]
